export const GET_DATA_LIST = "GET_DATA_LIST";
export const GET_DATA_SUCCESS = "GET_DATA_SUCCESS";
export const GET_DATA_ERROR = "GET_DATA_ERROR";

export const GET_DATA_ITEM = "GET_DATA_ITEM";
export const GET_DATA_ITEM_SUCCESS = "GET_DATA_ITEM_SUCCESS";
export const GET_DATA_ITEM_ERROR = "GET_DATA_ITEM_ERROR";

export const CREATE_TODO_ITEM = "CREATE_TODO_ITEM";
export const CREATE_TODO_SUCCESS = "CREATE_TODO_SUCCESS";
export const CREATE_TODO_ERROR = "CREATE_TODO_ERROR";

export const UPDATE_TODO_ITEM = "UPDATE_TODO_ITEM";
export const UPDATE_TODO_SUCCESS = "UPDATE_TODO_SUCCESS";
export const UPDATE_TODO_ERROR = "UPDATE_TODO_ERROR";

export const DELETE_TODO_ITEM = "DELETE_TODO_ITEM";
export const DELETE_TODO_SUCCESS = "DELETE_TODO_SUCCESS";
export const DELETE_TODO_ERROR = "DELETE_TODO_ERROR";